# -*- coding: utf-8 -*-
"""Image Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUNYkbtk_L23Z5cDh2ADCY5SDqYIarFn
"""

!pip install opendatasets --quiet

import opendatasets as od
od.download("https://www.kaggle.com/datasets/andrewmvd/animal-faces")

import torch
from torch import nn
from torch.optim import Adam
from torchvision.transforms import transforms
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from PIL import Image
import pandas as pd
import numpy as np
import os

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device available: " , device)

image_path = []
labels = []

for i in os.listdir("/content/animal-faces/afhq"):
  print(i)
  for label in os.listdir(f"/content/animal-faces/afhq/{i}"):
    print(label)
    for image in os.listdir(f"/content/animal-faces/afhq/{i}/{label}"):
      print(image)
      break
    break
  break

